### ISSUE TITLE
generic.cv.R

### ISSUE THREAD

**Issue by whizzalan** [pivotalsoftware/PivotalR#33]
May I use predict function with other output type?
like predict(object, newdata, type="response")
How do I do in fucntion generic.cv?

**Comment by walkingsparrow** [comment]
It is easy. Just do something like:
```
generic.cv(
    train=..., 
    predict=function(model, newdata) predict(model, newdata, type="response"), 
    metric=...., .....)
```
`generic.cv` also works with normal functions besides those from PivotalR. Recently I found `generic.cv` is very useful and flexible. It is easier to use than those similar functions in package 'caret'. Maybe I will send a pull request to add more examples to its manual.

**Comment by whizzalan** [comment]
Thanks a lot.
If it can use similar in package 'caret', that help me a lot.
It mean I can use a lot of algorithm in package 'caret'.
